services:
  - type: web
    name: streamlit-translator
    env: python
    buildCommand: pip install -r render_requirements.txt
    startCommand: streamlit run app.py --server.port=8080 --server.enableCORS=false
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
    plan: free